apiVersion: v1
kind: Pod
metadata:
  name: nginx-controller
spec:
  containers:
    - name: nginx
      image: nginx:latest
  tolerations:
    - key: "prod"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  # Will only apply while scheduling new pods  

      # NoExecute applies for existing pods as well
