apiVersion: v1
kind: Pod
metadata:
  name: nginx-controller
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80
  tolerations:
    - key: "prod"
      operator: "Equal"
      value: "false"
      effect: "NoExecute"  # Will only apply while scheduling new pods  

      # NoExecute applies for existing pods as well
