apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-deploy
  template:
    metadata:
     labels:
      app: web-deploy
    spec:
      containers:
      - name: web-deployment
        image: httpd
        ports:
        - containerPort: 80     